[INPUT_DATA]
path = ./data_oca/
cycle = cycle_0
sim_type = OCA_CGL5

[OUTPUT_DATA]
path = ./
name = OCA_CGL5_ewan
reduction = 2
laws = ['PP98']
quantities = [ ]
terms = [ ]
# reformat_oca_file.py --list-quantities

[PHYSICAL_PARAMS]
di = 1
